/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  trailingSlash: true,
  images: { unoptimized: true },
  // All remark/rehype/micromark/hast/unist packages are ESM-only.
  // transpilePackages tells Next.js webpack to bundle them (converting ESM → CJS-compatible).
  transpilePackages: [
    'unified',
    'remark-parse',
    'remark-math',
    'remark-rehype',
    'rehype-katex',
    'rehype-slug',
    'rehype-stringify',
    'github-slugger',
    'ccount',
    'character-entities-html4',
    'comma-separated-tokens',
    'decode-named-character-reference',
    'hast-util-from-dom',
    'hast-util-from-html',
    'hast-util-from-html-isomorphic',
    'hast-util-from-parse5',
    'hast-util-has-property',
    'hast-util-heading-rank',
    'hast-util-is-element',
    'hast-util-parse-selector',
    'hast-util-raw',
    'hast-util-to-html',
    'hast-util-to-parse5',
    'hast-util-to-string',
    'hast-util-to-text',
    'hast-util-whitespace',
    'hastscript',
    'html-void-elements',
    'mdast-util-definitions',
    'mdast-util-from-markdown',
    'mdast-util-to-hast',
    'micromark',
    'micromark-core-commonmark',
    'micromark-factory-destination',
    'micromark-factory-label',
    'micromark-factory-space',
    'micromark-factory-title',
    'micromark-factory-whitespace',
    'micromark-util-character',
    'micromark-util-chunked',
    'micromark-util-classify-character',
    'micromark-util-combine-extensions',
    'micromark-util-decode-numeric-character-reference',
    'micromark-util-decode-string',
    'micromark-util-encode',
    'micromark-util-html-tag-name',
    'micromark-util-normalize-identifier',
    'micromark-util-resolve-all',
    'micromark-util-sanitize-uri',
    'micromark-util-subtokenize',
    'micromark-util-symbol',
    'micromark-util-types',
    'parse5',
    'property-information',
    'space-separated-tokens',
    'stringify-entities',
    'unist-builder',
    'unist-util-find-after',
    'unist-util-generated',
    'unist-util-is',
    'unist-util-position',
    'unist-util-remove-position',
    'unist-util-stringify-position',
    'unist-util-visit',
    'unist-util-visit-parents',
    'vfile',
    'vfile-location',
    'vfile-message',
    'web-namespaces',
    'zwitch',
  ],
};
module.exports = nextConfig;
